= Arch Linux local mirror synchronizer
:icons: font

== Introduction

This project can be used to synchronize a local mirror of https://www.archlinux.org/[Arch Linux] packages using a script called link:sync[].
This mirror can be HTTP served locally by running the link:serve[] script (it requires ruby).

[NOTE]
.Related projects:
====
* https://github.com/paulojeronimo/archlinux-installer[archlinux-installer].
====

== Use

Copy the link:config.sample[] file to `config` and configure it as you want:

----
$ cp config.sample config
$ vim config
----

The mirror will be synchronized with `$MIRROR_BASE_URL`.
The local copy of the mirror will be downloaded in `$MIRROR_BASE_DIR`.
The HTTP server port used by this script is configured in `$HTTP_SERVER_PORT`.

[WARNING]
.Downloaded mirror size after `sync` (aproximately, on 2019 March):
====
----
$ du -hs mirror/
 38G	mirror/
----
====

[NOTE]
.Proxy settings:
====
If you are behind a proxy you may need to configure the `RSYNC_PROXY` variable before using the `sync` script.
Example: `$ export RSYNC_PROXY=user:password@proxy_host:proxy_port`
====

== References

. https://www.archlinux.org/mirrorlist/
. https://wiki.archlinux.org/index.php/Rsync
